name: java-build-custom-action
description: A custom GitHub Action for building Java projects using Maven.
inputs:
  java-version:
    description: it selects the java-version
    required: false
    default: '21'
  distribution:
    description: it slects the java distribution
    required: false
    default: 'temurin'
  working-directory:
    description: it selects the working directory to run
    required: false
    default: '.'
  artifact-name:
    description: it slects the artifact name
    required: false
    default: 'myjar'


outputs:
  code_test_output:
    value: ${{steps.test_tag.outputs.test_result}}
  code_build_output: 
    value: ${{steps.build_tag.outputs.build_result}}
  code_artifact_output:
    value: ${{steps.artifact_tag.outputs.artifact_result}}


runs:
  using: composite
  steps:
    - name: setup java
      uses: actions/setup-java@v4
      with:
        java-version: ${{inputs.java-version}}
        distribution: ${{inputs.distribution}}

    - name: run the tests
      id: test_tag
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        mvn test
        echo "test_result= maven test are completed successfully!" >> $GITHUB_OUTPUT
   
    - name: maven build
      id: build_tag
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        mvn clean package
        echo "build_result= Maven Build is completed successfully!" >> $GITHUB_OUTPUT

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.artifact-name}}
        path: target/*.jar

    - name: Artifact Summary
      shell: bash
      working-directory: ${{inputs.working-directory}}
      id: artifact_tag
      run: |
        echo "artifact_result= Artifact is uploaded successfully!" >> $GITHUB_OUTPUT
    
    - name: Summary of the java-build action
      shell: bash
      working-directory:
      run: |
        echo "${{steps.test_tag.outputs.test_result}}"
        echo "${{steps.build_tag.outputs.build_result}}"
        echo "${{steps.artifact_tag.outputs.artifact_result}}"
        


