name: docker-build-custom-action
description: This is custom action to build and push the docker image
inputs:
  working-directory:
    description: it selects the working directory to run
    required: false
    default: '.'
  image-name:
    required: true
  image-tag:
    required: true
  docker-username:
    required: true
  docker-password:
    required: true

outputs:
  docker_build_output: 
    value: ${{steps.dockbuild_tag.outputs.docbuild_result}}
  docker_push_output:
    value: ${{steps.dockpush_tag.outputs.docpush_result}}

runs:
  using: composite
  steps:
    - name: Docker Build
      id: docbuild_tag
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        docker build -t ${{inputs.image-name}}:${{inputs.image-tag}} .
        echo "docbuild_result= Docker Build is completed successfully!"  >> $GITHUB_OUTPUT

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{inputs.docker-username}}
        password: ${{inputs.docker-password}}

    - name: Dcoker Push
      id: docpush_tag
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        docker push ${{inputs.image-name}}:${{inputs.image-tag}}
        echo "docpush_result = Docker login and push completed successfully!"  >> $GITHUB_OUTPUT 

    - name: Docker Summary
      shell: bash
      working-directory:
      run: |
        echo "${{steps.docbuild_tag.outputs.docbuild_result}}"
        echo "${{steps.docpush_tag.outputs.docpush_result}}"
